services:
    rabbit_mq:
        container_name: rabbit
        image: rabbitmq:3.10-management
        expose:
            - 5672
        ports:
            - 15672:15672
        volumes:
            - rabbit_data:/var/lib/rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
            interval: 10s
            timeout: 5s
            retries: 3

    redis:
        image: redis:6.2.6
        container_name: redis
        volumes:
            - redis_data:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379
        command: redis-server /usr/local/etc/redis/redis.conf


    api:
        build:
            context: .
            dockerfile: api.DockerFile
        container_name: api
        expose:
            - 8000
        volumes:
            - api_data:/data
        depends_on:
            rabbit_mq:
                condition: service_healthy
            redis:
                condition: service_started

    websocket:
        build:
            context: .
            dockerfile: websocket.DockerFile
        container_name: websocket
        expose:
            - 8001
        volumes:
            - websocket_data:/data
        depends_on:
            rabbit_mq:
                condition: service_healthy

    worker:
        build:
            context: .
            dockerfile: worker.DockerFile
        container_name: worker
        volumes:
            - worker_data:/data
        depends_on:
            rabbit_mq:
                condition: service_healthy


volumes:
    rabbit_data:
    redis_data:
    api_data:
    websocket_data:
    worker_data:
