services:
    rabbit_mq:
        container_name: rabbit
        image: rabbitmq:3.10-management
        expose:
            - 5672
        ports:
            - 15672:15672
        volumes:
            - rabbit_data:/var/lib/rabbitmq

    redis:
        image: redis:6.2.6
        container_name: redis
        volumes:
            - redis_data:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379
        command: redis-server /usr/local/etc/redis/redis.conf


volumes:
    rabbit_data:
    redis_data:
